/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - Quantify records and measures across key business dimensions.
    - Understand the distribution of customers, products, orders and sales.

SQL Functions Used:
    - COUNT()
    - COUNT(DISTINCT)
    - SUM()
    - GROUP BY
    - ORDER BY
===============================================================================
*/

-- Customer distribution by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Customer distribution by country and city
SELECT
    country,
    city,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country, city
ORDER BY total_customers DESC;

-- Employee distribution by country
SELECT
    employee_country,
    COUNT(employee_key) AS total_employees
FROM gold.dim_employees
GROUP BY employee_country
ORDER BY total_employees DESC;

-- Employee distribution by city
SELECT
    employee_city,
    COUNT(employee_key) AS total_employees
FROM gold.dim_employees
GROUP BY employee_city
ORDER BY total_employees DESC;

-- Product distribution by category
SELECT
    category_name,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category_name
ORDER BY total_products DESC;

-- Product distribution by discontinued status
SELECT
    discontinued,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY discontinued
ORDER BY total_products DESC;

-- Unique orders by shipping timeline
SELECT
    shipping_timeline,
    COUNT(DISTINCT order_id) AS total_orders
FROM gold.fact_order_line
GROUP BY shipping_timeline
ORDER BY total_orders DESC;

-- Sales by shipping timeline
SELECT
    shipping_timeline,
    CAST(SUM(sales_amount) AS DECIMAL(18,2)) AS total_sales
FROM gold.fact_order_line
GROUP BY shipping_timeline
ORDER BY total_sales DESC;

-- Sales by product
SELECT
    p.product_name,
    CAST(SUM(o.sales_amount) AS DECIMAL(18,2)) AS total_sales
FROM gold.fact_order_line o
LEFT JOIN gold.dim_products p
    ON o.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_sales DESC;

-- Sales by product category
SELECT
    p.category_name,
    CAST(SUM(o.sales_amount) AS DECIMAL(18,2)) AS total_sales
FROM gold.fact_order_line o
LEFT JOIN gold.dim_products p
    ON o.product_key = p.product_key
GROUP BY p.category_name
ORDER BY total_sales DESC;

-- Sales generated by each employee
SELECT
    e.employee_name,
    CAST(SUM(o.sales_amount) AS DECIMAL(18,2)) AS total_sales
FROM gold.fact_order_line o
LEFT JOIN gold.dim_employees e
    ON o.employee_key = e.employee_key
GROUP BY e.employee_name
ORDER BY total_sales DESC;

-- Order lines handled by each employee
SELECT
    e.employee_name,
    COUNT(*) AS total_order_lines
FROM gold.fact_order_line o
LEFT JOIN gold.dim_employees e
    ON o.employee_key = e.employee_key
GROUP BY e.employee_name
ORDER BY total_order_lines DESC;

-- Unique orders handled by each employee
SELECT
    e.employee_name,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM gold.fact_order_line o
LEFT JOIN gold.dim_employees e
    ON o.employee_key = e.employee_key
GROUP BY e.employee_name
ORDER BY total_orders DESC;

-- Order lines handled by each shipping company
SELECT
    s.company_name,
    COUNT(*) AS total_order_lines
FROM gold.fact_order_line o
LEFT JOIN gold.dim_shippers s
    ON o.shipper_key = s.shipper_key
GROUP BY s.company_name
ORDER BY total_order_lines DESC;

-- Unique orders handled by each shipping company
SELECT
    s.company_name,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM gold.fact_order_line o
LEFT JOIN gold.dim_shippers s
    ON o.shipper_key = s.shipper_key
GROUP BY s.company_name
ORDER BY total_orders DESC;

-- Total items shipped by each shipping company
SELECT
    s.company_name,
    SUM(o.quantity) AS total_items_shipped
FROM gold.fact_order_line o
LEFT JOIN gold.dim_shippers s
    ON o.shipper_key = s.shipper_key
GROUP BY s.company_name
ORDER BY total_items_shipped DESC;

-- Sales handled by each shipping company
SELECT
    s.company_name,
    CAST(SUM(o.sales_amount) AS DECIMAL(18,2)) AS total_sales
FROM gold.fact_order_line o
LEFT JOIN gold.dim_shippers s
    ON o.shipper_key = s.shipper_key
GROUP BY s.company_name
ORDER BY total_sales DESC;